-- ============================================================================
-- Lahza payment gateway — checkout intents + webhook idempotency ledger
--
-- WHY a NEW table instead of widening public.subscriptions:
--   * `subscriptions` carries live production rows + the DB-enforced
--     `uq_subscriptions_one_active_per_clinic` invariant. Adding gateway columns
--     there would touch a table holding money-critical state for every tenant.
--   * The gateway-specific identity (reference / access_code / intent status) is
--     checkout state, not subscription state. Keeping it separate lets ANY
--     gateway (Lahza today, another tomorrow) be added without a schema rewrite
--     — the same "provider abstraction" rule as lib/payments/provider.ts.
--   * Activation still writes ONLY to pre-existing subscriptions columns
--     (plan_id, status, billing_status, current_period_*, billing_customer_id),
--     so no ALTER is required on that table at all.
-- ============================================================================
begin;

-- 1) Checkout intents — one row per gateway payment attempt -------------------
create table if not exists public.payment_checkout_intents (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'lahza',
  -- Gateway transaction reference (server-generated by US, never client input).
  reference text not null,
  clinic_id uuid not null references public.clinics(id) on delete cascade,
  plan_id text not null,
  billing_interval text not null default 'month'
    check (billing_interval in ('month', 'year', 'trial')),
  -- Minor units (cents for USD, agora/qirsh for ILS/JOD) — server-derived from
  -- the plan catalog; a client can never supply an amount.
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'expired')),
  authorization_url text,
  access_code text,
  customer_email text,
  created_by uuid references auth.users(id),
  paid_at timestamptz,
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A reference is unique PER PROVIDER: replaying another gateway's reference
  -- can never collide with this one.
  unique (provider, reference)
);

create index if not exists idx_payment_intents_clinic
  on public.payment_checkout_intents (clinic_id, created_at desc);
create index if not exists idx_payment_intents_pending
  on public.payment_checkout_intents (clinic_id) where status = 'pending';

drop trigger if exists set_updated_at_payment_checkout_intents on public.payment_checkout_intents;
create trigger set_updated_at_payment_checkout_intents
  before update on public.payment_checkout_intents
  for each row execute function public.set_updated_at();

-- 2) Lahza webhook ledger — durable idempotency (Lahza retries: every 3 min for
--    4 tries, then hourly for 72h in live; hourly for 72h in test) ------------
create table if not exists public.lahza_webhook_events (
  id uuid primary key default gen_random_uuid(),
  -- Lahza sends no Stripe-style event id, so the key is `<event>:<reference>`.
  event_key text not null unique,
  event text not null,
  reference text,
  clinic_id uuid references public.clinics(id) on delete set null,
  outcome text not null default 'processed'
    check (outcome in ('processed', 'skipped', 'error')),
  processed_at timestamptz not null default now()
);

create index if not exists idx_lahza_events_reference
  on public.lahza_webhook_events (reference);

-- 3) RLS ----------------------------------------------------------------------
alter table public.payment_checkout_intents enable row level security;
alter table public.lahza_webhook_events enable row level security;

-- Billing records are readable by the clinic's admins (owner/manager) only.
-- Writes happen exclusively through the service-role server client, so no
-- INSERT/UPDATE/DELETE policy is granted to `authenticated`.
drop policy if exists "view_payment_intents" on public.payment_checkout_intents;
create policy "view_payment_intents" on public.payment_checkout_intents for select
  using (
    public.app_is_super_admin()
    or public.app_user_is_clinic_admin_safe(clinic_id)
  );

-- Raw gateway events are server-side only: RLS on, no policy for `authenticated`
-- (identical posture to stripe_webhook_events).

-- 4) API privileges — explicit GRANTs (the 42501 lesson from #38) -------------
grant select on public.payment_checkout_intents to authenticated;
grant all privileges on public.payment_checkout_intents to service_role;
grant all privileges on public.lahza_webhook_events to service_role;

commit;

-- ----------------------------------------------------------------------------
-- REVERSIBILITY (documented; NOT executed):
--   drop table if exists public.lahza_webhook_events;
--   drop table if exists public.payment_checkout_intents;
-- ----------------------------------------------------------------------------
